services:
  store_manager:
    build: .
    container_name: store_manager_cli
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - labo02-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      
  mysql:
    image: mysql:8.4.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo02_db
      MYSQL_USER: labo02
      MYSQL_PASSWORD: labo02
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - labo02-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 10s

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - labo02-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  labo02-network:
    external: true
    
volumes:
  mysql_data:
